name: barn
input_image_path: ./assets/${name}.png
text_fg: '' # foreground text
text_bg: '' # background text

inpaint:
  inpaint_bg_path: ./cache/inpaint_bg_${name}.png
  outpainting: False #  
  outpaint_image_path: ./cache/outpaint_${name}.png

diffusion:
  cogvideo:
    prompt: 'clean community center or clubhouse, situated in a park-like setting. The building has a white and beige exterior, and it appears to be well-maintained. The surrounding area is a mix of grass and concrete, with a few trees nearby. There is no one present in the image, giving the place an empty and quiet atmosphere.'