name: christmas
input_image_path: ./assets_demo/${name}.png
text_fg: '' # foreground text
text_bg: '' # background text

inpaint:
  inpaint_bg_path: ./cache/inpaint_bg_${name}.png
  outpainting: False #  
  outpaint_image_path: ./cache/outpaint_${name}.png

diffusion:
  cogvideo:
    prompt: 'a nice bedroom with a bed and a chair, a table and a lamp, a window and a curtain.'
